language: python 
python: 
  - "3.6"

env:
  global:
    - OFFICIAL_REPO="n-wbrown/python_package_template"
    - ENV_NAME="python_package_template_env"
    - secure: "mnjKVGOn2UX9lTaee70k8AZthhZ9fTf1xQAvE6dPgCiArYOQ0oWPeR9ec51vMkbHxLVfxdW9b1Gnu4h8kGLPMoxt8GfMayyvcCPWQNpCTODpNMGhGg55nHWBj8NlrEJoiW52arTM4lOeYl9ix32ETdgu6aKIHHSlMUD2znt85py+UJyQcXIbalZnJf3n1xzaSAg5WkWVEjuS/zlgfov38GOhJhASoEtQTBCQZwFc9Kksy8vs1rxYmunbVrxuR4hU5DVTdVHMIOGCIU/H4TqvrALpkSsa6tetbS0wbqNpiQm/P5EaqdcVA/eCgU+4CF2Wxdgf3mG2+IuGdyNriVW8iDRpGatArUfF2NfeIWRJQcmS3lWZHsF99ETBmdvD1zwrHU/bLxGc//mRu4h5xYsF8sTBoZlOqmHhQ28coiKJdwkXzYN6IjUu5DrgsHaHHwqC6gOAkQ7Gjp7oXkVTBxa9K9hVvJZuW0/+ZRWy89lj1xGUNYSc7mONVxz5OUREwFcQ1OhKt4H7H7MFIWoYDIn5ZCtk8CvPyQZxTJNEzVBQUkIFIfNglh5DG/cYvnCjuSLYL1nU928DZv5RFnawyK+fqL54mdM1KjwhpL5UXLG7uqLc5G5l3EiqJMlj6ThsqjTb7c283oEmUM1sg8buuESKF0xzQzZshr84kPOQdQEs4Lg="

sudo: false

git:
  depth: 5

install:
  - sudo apt-get update
  # Install, configure conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  # conda-build and anaconda-client may be optional, check this later
  - conda install conda-build anaconda-client pip
  - conda update -q conda
  # Useful for debugging
  - conda info -a
  # Manage conda environment
  - conda create -n $ENV_NAME pip
  - source activate $ENV_NAME 
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - coverage run run_tests.py
  - coverage report -m 
  - |
    if [[ $TRAVIS_REPO_SLUG == $OFFICIAL_REPO ]]; then
      set -e
      pip install doctr
      cd docs
      make html
      cd ../
      doctr deploy . --built-docs docs/_build/html
    fi

after_success:
  - codecov
